<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Interest;
use App\Models\LibraryLocation;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $fictionLocation = LibraryLocation::where('section_name', 'Fiction')->where('shelf_number', 'F-01')->first();
        $scienceLocation = LibraryLocation::where('section_name', 'Science')->where('shelf_number', 'S-01')->first();
        $mathLocation = LibraryLocation::where('section_name', 'Mathematics')->where('shelf_number', 'M-01')->first();
        $englishLocation = LibraryLocation::where('section_name', 'English')->where('shelf_number', 'E-01')->first();
        $filipinoLocation = LibraryLocation::where('section_name', 'Filipino')->where('shelf_number', 'FL-01')->first();
        $historyLocation = LibraryLocation::where('section_name', 'History')->where('shelf_number', 'H-01')->first();
        $referenceLocation = LibraryLocation::where('section_name', 'Reference')->where('shelf_number', 'R-01')->first();

        $books = [
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'author' => 'J.K. Rowling',
                'isbn' => '9780747532699',
                'publisher' => 'Bloomsbury Publishing',
                'publication_date' => '1997-06-26',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility.',
                'genre' => 'Fantasy',
                'subject' => 'English',
                'shelf' => 'F-01',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
            [
                'title' => 'Harry Potter and the Chamber of Secrets',
                'author' => 'J.K. Rowling',
                'isbn' => '9780747538493',
                'publisher' => 'Bloomsbury Publishing',
                'publication_date' => '1998-07-02',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry.',
                'genre' => 'Fantasy',
                'subject' => 'English',
                'shelf' => 'F-01',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'isbn' => '9780439023528',
                'publisher' => 'Scholastic Press',
                'publication_date' => '2008-09-14',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts.',
                'genre' => 'Dystopian',
                'subject' => 'English',
                'shelf' => 'F-02',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '9780061120084',
                'publisher' => 'J.B. Lippincott & Co.',
                'publication_date' => '1960-07-11',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.',
                'genre' => 'Fiction',
                'subject' => 'English',
                'shelf' => 'F-03',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'isbn' => '9780743273565',
                'publisher' => 'Charles Scribner\'s Sons',
                'publication_date' => '1925-04-10',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'A portrait of the Jazz Age in all of its decadence and excess.',
                'genre' => 'Fiction',
                'subject' => 'English',
                'shelf' => 'F-03',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
            [
                'title' => 'A Brief History of Time',
                'author' => 'Stephen Hawking',
                'isbn' => '9780553380163',
                'publisher' => 'Bantam Books',
                'publication_date' => '1988-04-01',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'From the Big Bang to black holes, Hawking explores the fundamental questions of the universe.',
                'genre' => 'Non-Fiction',
                'subject' => 'Science',
                'shelf' => 'S-01',
                'library_section' => 'Science',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $scienceLocation?->id,
            ],
            [
                'title' => 'The Selfish Gene',
                'author' => 'Richard Dawkins',
                'isbn' => '9780198788607',
                'publisher' => 'Oxford University Press',
                'publication_date' => '1976-01-01',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'An exploration of evolution from the perspective of genes.',
                'genre' => 'Non-Fiction',
                'subject' => 'Science',
                'shelf' => 'S-02',
                'library_section' => 'Science',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $scienceLocation?->id,
            ],
            [
                'title' => 'Calculus: Early Transcendentals',
                'author' => 'James Stewart',
                'isbn' => '9781285741550',
                'publisher' => 'Cengage Learning',
                'publication_date' => '2015-01-01',
                'edition' => '8th',
                'language' => 'English',
                'description' => 'Comprehensive calculus textbook for university students.',
                'genre' => 'Textbook',
                'subject' => 'Mathematics',
                'shelf' => 'M-01',
                'library_section' => 'Mathematics',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $mathLocation?->id,
            ],
            [
                'title' => 'Noli Me Tangere',
                'author' => 'Jose Rizal',
                'isbn' => '9789710837845',
                'publisher' => 'Berlin Publishing',
                'publication_date' => '1887-03-29',
                'edition' => '1st',
                'language' => 'Filipino',
                'description' => 'The seminal Philippine novel exposing Spanish colonial abuses.',
                'genre' => 'Historical Fiction',
                'subject' => 'Filipino',
                'shelf' => 'FL-01',
                'library_section' => 'Filipino',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $filipinoLocation?->id,
            ],
            [
                'title' => 'El Filibusterismo',
                'author' => 'Jose Rizal',
                'isbn' => '9789710837852',
                'publisher' => 'Ghent Publishing',
                'publication_date' => '1891-09-18',
                'edition' => '1st',
                'language' => 'Filipino',
                'description' => 'The sequel to Noli Me Tangere, continuing the struggle for reform.',
                'genre' => 'Historical Fiction',
                'subject' => 'Filipino',
                'shelf' => 'FL-01',
                'library_section' => 'Filipino',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $filipinoLocation?->id,
            ],
            [
                'title' => 'Philippine History: A Comprehensive Guide',
                'author' => 'Teodoro Agoncillo',
                'isbn' => '9789710837869',
                'publisher' => 'UP Press',
                'publication_date' => '1990-01-01',
                'edition' => '2nd',
                'language' => 'English',
                'description' => 'A comprehensive overview of Philippine history from pre-colonial to modern times.',
                'genre' => 'Non-Fiction',
                'subject' => 'History',
                'shelf' => 'H-01',
                'library_section' => 'History',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $historyLocation?->id,
            ],
            [
                'title' => 'World History: Patterns of Civilization',
                'author' => 'Peter N. Stearns',
                'isbn' => '9780131234567',
                'publisher' => 'Pearson',
                'publication_date' => '2010-01-01',
                'edition' => '5th',
                'language' => 'English',
                'description' => 'Global history textbook covering major civilizations and their interactions.',
                'genre' => 'Textbook',
                'subject' => 'History',
                'shelf' => 'H-02',
                'library_section' => 'History',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $historyLocation?->id,
            ],
            [
                'title' => 'The Oxford English Dictionary',
                'author' => 'Oxford University Press',
                'isbn' => '9780198611868',
                'publisher' => 'Oxford University Press',
                'publication_date' => '1989-03-01',
                'edition' => '2nd',
                'language' => 'English',
                'description' => 'The definitive record of the English language.',
                'genre' => 'Reference',
                'subject' => 'Reference',
                'shelf' => 'R-01',
                'library_section' => 'Reference',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $referenceLocation?->id,
            ],
            [
                'title' => 'The Lord of the Rings: The Fellowship of the Ring',
                'author' => 'J.R.R. Tolkien',
                'isbn' => '9780547928210',
                'publisher' => 'Houghton Mifflin',
                'publication_date' => '1954-07-29',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'The first volume of the epic fantasy trilogy.',
                'genre' => 'Fantasy',
                'subject' => 'English',
                'shelf' => 'F-02',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'isbn' => '9780141439518',
                'publisher' => 'T. Egerton',
                'publication_date' => '1813-01-28',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'A romantic novel of manners set in Regency England.',
                'genre' => 'Romance',
                'subject' => 'English',
                'shelf' => 'F-03',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'isbn' => '9780451524935',
                'publisher' => 'Secker & Warburg',
                'publication_date' => '1949-06-08',
                'edition' => '1st',
                'language' => 'English',
                'description' => 'A dystopian social science fiction novel.',
                'genre' => 'Dystopian',
                'subject' => 'English',
                'shelf' => 'F-02',
                'library_section' => 'Fiction',
                'status' => 'available',
                'source' => 'gsa',
                'library_location_id' => $fictionLocation?->id,
            ],
        ];

        foreach ($books as $bookData) {
            $book = Book::firstOrCreate(
                ['isbn' => $bookData['isbn']],
                $bookData
            );

            // Attach categories
            $genre = Interest::where('name', $bookData['genre'])->where('type', 'genre')->first();
            $subject = Interest::where('name', $bookData['subject'])->where('type', 'subject')->first();

            if ($genre) {
                $book->categories()->syncWithoutDetaching([$genre->id]);
            }
            if ($subject) {
                $book->categories()->syncWithoutDetaching([$subject->id]);
            }
        }
    }
}